stages:
   # - build
   - test_cmd_show
   - test_speed_interface
   - test_check_ip_bridge
   - report
#   - test

# software_update:
#    stage: build
#    script:
#     - ./scripts/upload.sh

# static_lag-test:
#   stage: test
#   script:
#     - echo "Static_lag test running"
#     - pip install -r requirements.txt
#     - pytest tests/test_static_lag.py --maxfail=1 --disable-warnings -v

# lag-test:
#   stage: test
#   script:
#     - echo "LAG test running"
#     - pytest tests/test_lag.py --maxfail=1 --disable-warnings -v
#   needs:
#     - static_lag-test

# subinterface-test:
#   stage: test
#   script:
#     - echo "Subinterface test running"
#     - pytest tests/test_subinterface.py --maxfail=1 --disable-warnings -v
#   needs:
#     - lag-test

image: python:3.10-slim
default:
  tags:
    - br100

test_cmd_show:
   stage: test_cmd_show
   image: python
   artifacts:
      when: always
      expire_in: 5 days
      paths:
            - backend/tests/report_html
   before_script:
      - apt-get update
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
   script:
      - cd backend/tests
      - pytest -v --html=report_html/BULAT_TEST.html test_cmd_show.py 
   allow_failure: true
   after_script:
      - cd backend/tests

test_speed_interface:
   stage: test_speed_interface
   image: python
   artifacts:
      when: always
      expire_in: 5 days
      paths:
            - backend/tests/report_html
   before_script:
      - apt-get update
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
   script:
      - cd backend/tests
      - pytest -v --html=report_html/BULAT_TEST.html test_check_speed_interf.py 
      - pytest -v --html=report_html/BULAT_TEST.html test_check_ip_bridge.py 

   allow_failure: true
   after_script:
      - cd backend/tests


test_check_ip_bridge:
   stage: test_check_ip_bridge
   image: python
   artifacts:
      when: always
      expire_in: 5 days
      paths:
            - backend/tests/report_html
   before_script:
      - apt-get update
      - pip install --upgrade pip
      - pip install -r backend/requirements.txt
   script:
      - cd backend/tests
      - pytest -v --html=report_html/BULAT_TEST.html test_check_ip_bridge.py 
   allow_failure: true
   after_script:
      - cd backend/tests

pages:
  stage: report

  script:
    - mkdir html-report_public
    - cp -r backend/tests/report_html/* html-report_public
    
  artifacts:
    when: always
    expire_in: never
    paths:
        - html-report_public