workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

image: python:3.10-slim
default:
  tags:
    - br100

stages:
    - test
    
run_test:
    stage: test
    image: python
    before_script:
        - apt-get update
        - pip install --upgrade pip
        - pip install -r backend/requirements.txt
    script:
        - cd backend/tests
        - pytest test_commands_show.py -v